<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE 
students 
[<!ELEMENT student (name, telephone, address)+>
<!ATTLIST student
	login ID #REQUIRED
	faculty CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT address (country, city, street)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
]
>
<students>
	<student login="mit" faculty="mmf">
		<name>Mitar Alex</name>
		<telephone>2456474</telephone>
		<address>
			<country>Belarus</country>
			<city>Minsk</city>
			<street>Kalinovsky 45</street>
		</address>
	</student>
	<student login="pus" faculty="mmf">
		<name>Pashkun Alex</name>
		<telephone>3453789</telephone>
		<address>
			<country>Belarus</country>
			<city>Brest</city>
			<street>Knorina 56</street>
		</address>
	</student>
</students>